//! Actuator-side parameters, compensation, and output-axis estimates.
//!
//! The compensation layer sits above the inner electrical current loop. It
//! turns output-axis feedback torque into a bounded output torque command by
//! adding calibrated friction, inertial, and known-load feedforward terms.
//!
//! Friction compensation uses a hybrid signal policy:
//!
//! - near zero speed, breakaway direction follows the commanded motion hint so
//!   the controller can push through the deadzone without waiting for noisy
//!   measured motion
//! - once motion is established, Coulomb and viscous drag compensation follow
//!   the measured output velocity
//!
//! That split keeps startup and reversal behavior decisive while making viscous
//! drag compensation track the real actuator speed instead of a fixed
//! pseudo-velocity.
//!
//! # Reference plot
//!
//! The following SVG is generated by `cargo run -p fluxkit-pmsm-sim --example
//! closed_loop_actuator_compensation --
//! docs/plots/closed_loop_actuator_compensation.svg` and shows the intended
//! usage: a compensated controller breaking away more cleanly against a
//! repeatable output-side bias load while exposing a torque breakdown for
//! tuning.
#![doc = include_str!("../../../docs/plots/closed_loop_actuator_compensation.svg")]

use fluxkit_math::{
    MechanicalAngle,
    units::{NewtonMeters, RadPerSec},
};

/// Static actuator parameters that map motor-shaft behavior to the output axis.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ActuatorParams {
    /// Mechanical reduction ratio from motor shaft to output axis.
    ///
    /// A value of `5.0` means the motor rotates five turns for one output-axis turn.
    pub gear_ratio: f32,
    /// Optional output-axis mechanical speed limit.
    pub max_output_velocity: Option<RadPerSec>,
    /// Optional output-axis continuous torque limit.
    pub max_output_torque: Option<NewtonMeters>,
    /// Optional calibrated mechanical and load-side compensation model.
    pub compensation: ActuatorCompensationConfig,
}

/// Output-axis estimate supplied by platform code.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ActuatorEstimate {
    /// Wrapped output-axis angle from the output encoder.
    pub output_angle: MechanicalAngle,
    /// Output-axis mechanical velocity estimate.
    pub output_velocity: RadPerSec,
}

/// Optional mechanical and load-side compensation parameters.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ActuatorCompensationConfig {
    /// Friction and drag compensation.
    pub friction: FrictionCompensation,
    /// Acceleration-related inertial feedforward.
    pub inertia: InertiaCompensation,
    /// Known constant load or bias torque.
    pub load: LoadCompensation,
    /// Absolute bound on the summed compensation torque.
    pub max_total_torque: NewtonMeters,
}

impl ActuatorCompensationConfig {
    /// Returns a fully disabled compensation configuration.
    pub const fn disabled() -> Self {
        Self {
            friction: FrictionCompensation::disabled(),
            inertia: InertiaCompensation::disabled(),
            load: LoadCompensation::disabled(),
            max_total_torque: NewtonMeters::ZERO,
        }
    }
}

/// Direction-dependent friction and drag compensation.
///
/// The controller uses these parameters in two regimes:
///
/// - breakaway compensation is guided by commanded direction near zero speed
/// - Coulomb and viscous compensation transition onto measured output velocity
///   as the actuator starts moving
///
/// `zero_velocity_blend_band` defines the width of that transition.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FrictionCompensation {
    /// Enables friction and drag compensation.
    pub enabled: bool,
    /// Additional startup torque near zero speed in the positive direction.
    pub positive_breakaway_torque: NewtonMeters,
    /// Additional startup torque near zero speed in the negative direction.
    pub negative_breakaway_torque: NewtonMeters,
    /// Constant friction torque while moving in the positive direction.
    pub positive_coulomb_torque: NewtonMeters,
    /// Constant friction torque while moving in the negative direction.
    pub negative_coulomb_torque: NewtonMeters,
    /// Positive-direction viscous coefficient in `Nm / (rad/s)`.
    pub positive_viscous_coefficient: f32,
    /// Negative-direction viscous coefficient in `Nm / (rad/s)`.
    pub negative_viscous_coefficient: f32,
    /// Smoothing band around zero speed used to avoid discontinuous switching
    /// and to blend from command-guided breakaway behavior into
    /// measurement-driven drag compensation.
    pub zero_velocity_blend_band: RadPerSec,
}

impl FrictionCompensation {
    /// Returns friction compensation disabled with zeroed coefficients.
    pub const fn disabled() -> Self {
        Self {
            enabled: false,
            positive_breakaway_torque: NewtonMeters::ZERO,
            negative_breakaway_torque: NewtonMeters::ZERO,
            positive_coulomb_torque: NewtonMeters::ZERO,
            negative_coulomb_torque: NewtonMeters::ZERO,
            positive_viscous_coefficient: 0.0,
            negative_viscous_coefficient: 0.0,
            zero_velocity_blend_band: RadPerSec::ZERO,
        }
    }
}

/// Acceleration-related inertial feedforward.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InertiaCompensation {
    /// Enables inertial feedforward.
    pub enabled: bool,
    /// Reflected output-side inertia in `kg m^2`.
    pub reflected_inertia_kg_m2: f32,
    /// Absolute clamp on the commanded acceleration used for feedforward, in `rad/s^2`.
    pub max_acceleration_rad_per_sec2: f32,
}

impl InertiaCompensation {
    /// Returns inertial compensation disabled with zeroed coefficients.
    pub const fn disabled() -> Self {
        Self {
            enabled: false,
            reflected_inertia_kg_m2: 0.0,
            max_acceleration_rad_per_sec2: 0.0,
        }
    }
}

/// Known load or bias torque compensation.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct LoadCompensation {
    /// Enables constant known-load compensation.
    pub enabled: bool,
    /// Constant output-axis torque bias.
    pub constant_bias_torque: NewtonMeters,
}

impl LoadCompensation {
    /// Returns load compensation disabled with zero bias.
    pub const fn disabled() -> Self {
        Self {
            enabled: false,
            constant_bias_torque: NewtonMeters::ZERO,
        }
    }
}

/// Per-cycle actuator compensation telemetry.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ActuatorCompensationTelemetry {
    /// Feedback-produced output torque request before compensation.
    pub feedback_torque: NewtonMeters,
    /// Friction and drag compensation contribution.
    ///
    /// This includes any active breakaway, Coulomb, and viscous terms after
    /// the near-zero blending logic is applied.
    pub friction_torque: NewtonMeters,
    /// Inertial feedforward contribution.
    pub inertia_torque: NewtonMeters,
    /// Known-load compensation contribution.
    pub load_torque: NewtonMeters,
    /// Total bounded additive compensation contribution.
    pub total_compensation_torque: NewtonMeters,
    /// Final bounded output torque command after adding compensation.
    pub total_output_torque_command: NewtonMeters,
}

impl ActuatorCompensationTelemetry {
    /// Returns a zeroed telemetry snapshot.
    pub const fn zero() -> Self {
        Self {
            feedback_torque: NewtonMeters::ZERO,
            friction_torque: NewtonMeters::ZERO,
            inertia_torque: NewtonMeters::ZERO,
            load_torque: NewtonMeters::ZERO,
            total_compensation_torque: NewtonMeters::ZERO,
            total_output_torque_command: NewtonMeters::ZERO,
        }
    }
}
