//! Dynamic PMSM plant state and snapshots.

use fluxkit_math::{
    ElectricalAngle, MechanicalAngle,
    frame::{Abc, AlphaBeta, Dq},
    modulation::PhaseDuty,
    units::{Amps, NewtonMeters, RadPerSec, Volts},
};

/// Dynamic PMSM plant state.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PmsmState {
    /// Unwrapped mechanical rotor angle.
    pub mechanical_angle: MechanicalAngle,
    /// Mechanical rotor velocity.
    pub mechanical_velocity: RadPerSec,
    /// `d/q` current state.
    pub current_dq: Dq<Amps>,
}

/// Snapshot produced after one plant integration step.
#[derive(Clone, Copy, Debug, PartialEq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PmsmSnapshot {
    /// Updated dynamic state.
    pub state: PmsmState,
    /// Wrapped electrical rotor angle corresponding to the state.
    pub electrical_angle: ElectricalAngle,
    /// Wrapped mechanical rotor angle corresponding to the state.
    pub wrapped_mechanical_angle: MechanicalAngle,
    /// Wrapped output-axis angle corresponding to the state.
    pub wrapped_output_angle: MechanicalAngle,
    /// Output-axis mechanical velocity corresponding to the state.
    pub output_velocity: RadPerSec,
    /// `abc` current vector derived from the updated `d/q` current state.
    pub phase_currents: Abc<Amps>,
    /// `alpha/beta` voltage actually applied to the plant over the step.
    pub applied_alpha_beta: AlphaBeta<Volts>,
    /// `d/q` voltage corresponding to the applied voltage at the end-of-step angle.
    pub applied_vdq: Dq<Volts>,
    /// Zero-sum phase-voltage vector actually applied to the plant.
    pub phase_voltage: Abc<Volts>,
    /// Phase duty used for the step when duty-based stepping is used.
    pub phase_duty: Option<PhaseDuty>,
    /// Electromagnetic torque generated by the updated state.
    pub electromagnetic_torque: NewtonMeters,
    /// Output-side actuator parasitic torque evaluated at the updated state.
    pub actuator_parasitic_torque: NewtonMeters,
}
